package memre.roomdemo

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.LiveData
import memre.roomdemo.data.ITodoRepository
import memre.roomdemo.data.Todo
import memre.roomdemo.data.TodoRepository
import java.util.Date

class MainActivityViewModel(application: Application) : AndroidViewModel(application) {

    private val todoRepository: ITodoRepository = TodoRepository(application)

    val todos: LiveData<List<Todo>>
        get() = todoRepository.getTodos()

    fun addTodo(text: String) {
        todoRepository.addTodo(
            // Notice the id is set to 0. It will be replaced with an autogenerated value.
            Todo(0, false, text, Date().time)
        )
    }

    fun deleteTodo(id: Int) {
        todoRepository.deleteTodo(id)
    }

    fun editTodoText(id: Int, text: String) {
        todoRepository.editTodoText(id, text)
    }

    fun editTodoDone(id: Int, done: Boolean) {
        todoRepository.editTodoDone(id, done)
    }
}